import React, { useMemo, useState } from 'react';
import { AreaSummary, api } from '../services/api';
import { useToast } from '../context/ToastContext';
import { useAuth } from '../context/AuthContext';
import { X, ShieldCheck, MapPin, CalendarDays, Activity, Pill, Stethoscope, Building2, UploadCloud, CheckCircle2, Droplets, Siren, Hospital, Bug, FlaskConical, ClipboardCheck, FileText } from 'lucide-react';

interface AddObservationModalProps { isOpen:boolean; onClose:()=>void; areas:AreaSummary[]; onObservationAdded:()=>void; }
const PROVIDER_LABELS:Record<string,string>={PRIVATE_CLINIC:'Private Clinic',GOVERNMENT_CLINIC:'Government Clinic',HOSPITAL:'Hospital',DOCTOR:'Doctor',MUNICIPAL_HEALTH_AUTHORITY:'Municipal Health Authority',GOVERNMENT_HEALTH_OFFICIAL:'Government Health Official'};
const DISEASES=['Dengue','Malaria','Chikungunya','Influenza / ILI','Acute Diarrhoeal Disease','Typhoid'];
function recommendedDisease(){const m=new Date().getMonth()+1;if([6,7,8,9,10].includes(m))return'Dengue';if([3,4,5].includes(m))return'Acute Diarrhoeal Disease';return'Influenza / ILI';}
const LEVEL_OPTIONS={medicine:['Below normal','Normal','Elevated','Very high'],vector:['Low','Moderate','High','Critical'],environment:['None','Localized','Widespread','Severe']};

type Values=Record<string,string>;
export const AddObservationModal:React.FC<AddObservationModalProps>=({isOpen,onClose,areas,onObservationAdded})=>{
 const {user,canAddObservations}=useAuth();const{showToast}=useToast();const today=new Date().toISOString().split('T')[0];const recommended=useMemo(()=>recommendedDisease(),[]);
 const[areaId,setAreaId]=useState(areas[0]?.rawId||0);const[observedOn,setObservedOn]=useState(today);const[disease,setDisease]=useState(recommended);const[v,setV]=useState<Values>({});const[submitting,setSubmitting]=useState(false);
 if(!isOpen||!canAddObservations)return null;const providerLabel=PROVIDER_LABELS[user?.provider_type||'']||'Authorized Health Data Provider';const selectedArea=areas.find(a=>a.rawId===areaId);const set=(k:string,x:string)=>setV(s=>({...s,[k]:x}));const reset=()=>{setAreaId(areas[0]?.rawId||0);setObservedOn(today);setDisease(recommended);setV({});};
 const submit=async(e:React.FormEvent)=>{e.preventDefault();if(!areaId){showToast('error','Area Required','Select the reporting area.');return;}const n=(k:string)=>Number(v[k])||0;const levels=['medicineDemandLevel','vectorActivityLevel','environmentalLevel'];if(![...levels,'suspectedCases','confirmedCases','labPositivityRate','feverPresentations','respiratorySymptoms','giSymptoms','opdVisits','hospitalAdmissions','emergencyVisits'].some(k=>v[k])){showToast('error','Information Required','Please provide at least one surveillance observation.');return;}setSubmitting(true);try{const result=await api.createProviderObservation({area_id:areaId,observed_on:observedOn,disease,suspected_cases:n('suspectedCases'),confirmed_cases:n('confirmedCases'),lab_positivity_rate:n('labPositivityRate'),fever_presentations:n('feverPresentations'),respiratory_symptoms:n('respiratorySymptoms'),gi_symptoms:n('giSymptoms'),opd_visits:n('opdVisits'),hospital_admissions:n('hospitalAdmissions'),emergency_visits:n('emergencyVisits'),medicine_demand_level:v.medicineDemandLevel||'Normal',vector_activity_level:v.vectorActivityLevel||'Low',environmental_contamination_level:v.environmentalLevel||'None',additional_observations:v.additionalObservations||'',action_or_verification_needed:v.actionNeeded||'',data_quality_score:.95} as any);showToast('success','Information Uploaded',`${providerLabel}: ${result.message} Risk score: ${result.assessment?.risk_score??'updated'}/100.`);onObservationAdded();reset();onClose();}catch(err:any){showToast('error','Upload Failed',err.message||'Could not save surveillance information.');}finally{setSubmitting(false);}};
 return <div className="fixed inset-0 z-50 flex items-center justify-center p-4 bg-slate-950/85 backdrop-blur-md"><div className="relative w-full max-w-4xl max-h-[94vh] overflow-y-auto rounded-[28px] border border-white/10 bg-slate-950 shadow-2xl"><div className="absolute inset-x-0 top-0 h-44 bg-gradient-to-br from-cyan-500/30 via-blue-600/20 to-emerald-500/10 pointer-events-none"/><button onClick={onClose} className="absolute right-4 top-4 z-10 rounded-xl p-2 text-slate-400 hover:bg-white/10 hover:text-white"><X className="h-5 w-5"/></button>
 <div className="relative px-6 pb-5 pt-6"><div className="flex items-start gap-3"><div className="rounded-2xl border border-cyan-300/20 bg-cyan-300/10 p-3 text-cyan-200"><ShieldCheck className="h-6 w-6"/></div><div><div className="flex flex-wrap items-center gap-2"><h2 className="text-xl font-black text-white">Official Health Information</h2><span className="rounded-full border border-emerald-400/20 bg-emerald-400/10 px-2 py-1 text-[10px] font-bold uppercase text-emerald-300">Authorized</span></div><p className="mt-1 text-xs text-slate-300">Professional surveillance form — each question captures a different signal used by the risk-assessment system.</p><div className="mt-3 inline-flex items-center gap-2 rounded-full border border-blue-300/15 bg-blue-400/10 px-3 py-1.5 text-[11px] font-semibold text-blue-100"><Building2 className="h-3.5 w-3.5"/>{providerLabel}</div></div></div></div>
 <form onSubmit={submit} className="relative space-y-4 px-6 pb-6"><div className="grid gap-3 sm:grid-cols-2"><Field label="Reporting Area" icon={<MapPin/>}><select value={areaId} onChange={e=>setAreaId(Number(e.target.value))} className="input">{areas.map(a=><option key={a.rawId} value={a.rawId}>{a.name} — {a.district}</option>)}</select>{selectedArea&&<small>Dashboard target: {selectedArea.name}</small>}</Field><Field label="Record Date" icon={<CalendarDays/>}><input className="input" type="date" value={observedOn} onChange={e=>setObservedOn(e.target.value)}/></Field><Field label="Priority Disease" icon={<Activity/>}><select className="input" value={disease} onChange={e=>setDisease(e.target.value)}>{DISEASES.map(x=><option key={x}>{x}{x===recommended?' — Recommended now':''}</option>)}</select></Field></div>
 <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="mb-3"><p className="text-sm font-bold text-white">Clinical & Surveillance Findings</p><p className="text-[10px] text-slate-500">Use the reporting period represented by the record date. Percentages should be based on tests performed during that period.</p></div><div className="grid gap-3 sm:grid-cols-2 lg:grid-cols-3"><Number label="Suspected Cases" help="Suspected cases for selected disease" icon={<ClipboardCheck/>} v={v} set={set} k="suspectedCases"/><Number label="Confirmed Cases" help="Laboratory/clinically confirmed" icon={<CheckCircle2/>} v={v} set={set} k="confirmedCases"/><Percent label="Lab Positivity Rate" help="Positive tests ÷ tests performed" v={v} set={set} k="labPositivityRate"/><Number label="Fever Presentations" help="Patients presenting with fever" icon={<Stethoscope/>} v={v} set={set} k="feverPresentations"/><Number label="Respiratory Symptoms" help="ILI/respiratory presentations" icon={<Activity/>} v={v} set={set} k="respiratorySymptoms"/><Number label="GI Symptoms" help="Diarrhoeal/GI presentations" icon={<Activity/>} v={v} set={set} k="giSymptoms"/><Number label="OPD Consultations" help="Relevant outpatient consultations" icon={<Hospital/>} v={v} set={set} k="opdVisits"/><Number label="Hospital Admissions" help="Relevant inpatient admissions" icon={<Hospital/>} v={v} set={set} k="hospitalAdmissions"/><Number label="Emergency Visits" help="Relevant emergency presentations" icon={<Siren/>} v={v} set={set} k="emergencyVisits"/></div></section>
 <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="mb-3"><p className="text-sm font-bold text-white">Context & Environmental Signals</p><p className="text-[10px] text-slate-500">Choose the professional assessment that best represents your reporting area.</p></div><div className="grid gap-3 md:grid-cols-3"><SelectField label="Medicine Demand Level" help="Compared with usual demand" icon={<Pill/>} value={v.medicineDemandLevel||'Normal'} onChange={x=>set('medicineDemandLevel',x)} options={LEVEL_OPTIONS.medicine}/><SelectField label="Vector Activity Level" help="Mosquito/vector activity observed" icon={<Bug/>} value={v.vectorActivityLevel||'Low'} onChange={x=>set('vectorActivityLevel',x)} options={LEVEL_OPTIONS.vector}/><SelectField label="Environmental Contamination" help="Water/food contamination concern" icon={<Droplets/>} value={v.environmentalLevel||'None'} onChange={x=>set('environmentalLevel',x)} options={LEVEL_OPTIONS.environment}/></div></section>
 <section className="rounded-2xl border border-slate-800 bg-slate-900/60 p-4"><div className="mb-3 flex items-center gap-2"><FileText className="h-4 w-4 text-cyan-300"/><div><p className="text-sm font-bold text-white">Professional Notes</p><p className="text-[10px] text-slate-500">Optional context that structured numbers cannot capture.</p></div></div><div className="grid gap-3 md:grid-cols-2"><TextArea label="Additional Observations" placeholder="Unusual cluster, locality pattern, seasonal change, notable symptoms…" value={v.additionalObservations||''} onChange={x=>set('additionalObservations',x)}/><TextArea label="Action / Verification Needed" placeholder="Field verification, testing, vector control, stock review, advisory needed…" value={v.actionNeeded||''} onChange={x=>set('actionNeeded',x)}/></div></section>
 <div className="flex items-start gap-2 rounded-xl border border-emerald-400/10 bg-emerald-400/5 p-3 text-[10px] leading-relaxed text-emerald-100/80"><CheckCircle2 className="mt-0.5 h-4 w-4 shrink-0 text-emerald-300"/>Aggregate surveillance only. Do not enter patient names, phone numbers, addresses, Aadhaar numbers or other personally identifying information.</div><button disabled={submitting} className="flex w-full items-center justify-center gap-2 rounded-xl bg-gradient-to-r from-cyan-500 to-blue-600 px-4 py-3.5 text-sm font-black text-white disabled:opacity-60"><UploadCloud className="h-4 w-4"/>{submitting?'Processing & Updating Dashboard…':'Upload Information & Recalculate Risk'}</button></form></div></div>;
};
function Field({label,icon,children}:{label:string;icon:React.ReactNode;children:React.ReactNode}){return <label className="block"><span className="mb-1.5 flex items-center gap-1 text-[11px] font-bold uppercase tracking-wider text-slate-400">{React.cloneElement(icon as React.ReactElement,{className:'h-3.5 w-3.5 text-cyan-300'})}{label}</span>{children}</label>}
function Number({label,help,icon,v,set,k}:{label:string;help:string;icon:React.ReactNode;v:Values;set:(k:string,x:string)=>void;k:string}){return <label className="block rounded-xl border border-slate-800 bg-slate-950/50 p-3"><span className="flex items-center gap-1.5 text-[10px] font-bold text-slate-300">{icon}{label}</span><span className="mt-1 block text-[9px] text-slate-600">{help}</span><input type="number" min="0" step="1" value={v[k]||''} onChange={e=>set(k,e.target.value)} placeholder="Enter value" className="input mt-2"/></label>}
function Percent({label,help,v,set,k}:{label:string;help:string;v:Values;set:(k:string,x:string)=>void;k:string}){return <label className="block rounded-xl border border-slate-800 bg-slate-950/50 p-3"><span className="flex items-center gap-1.5 text-[10px] font-bold text-slate-300"><FlaskConical className="h-3.5 w-3.5 text-cyan-300"/>{label}</span><span className="mt-1 block text-[9px] text-slate-600">{help}</span><div className="relative mt-2"><input type="number" min="0" max="100" step="0.1" value={v[k]||''} onChange={e=>set(k,e.target.value)} placeholder="0–100" className="input pr-10"/><span className="absolute right-3 top-2.5 text-xs text-slate-500">%</span></div></label>}
function SelectField({label,help,icon,value,onChange,options}:{label:string;help:string;icon:React.ReactNode;value:string;onChange:(x:string)=>void;options:string[]}){return <label className="block rounded-xl border border-slate-800 bg-slate-950/50 p-3"><span className="flex items-center gap-1.5 text-[10px] font-bold text-slate-300">{icon}{label}</span><span className="mt-1 block text-[9px] text-slate-600">{help}</span><select className="input mt-2" value={value} onChange={e=>onChange(e.target.value)}>{options.map(x=><option key={x}>{x}</option>)}</select></label>}
function TextArea({label,placeholder,value,onChange}:{label:string;placeholder:string;value:string;onChange:(x:string)=>void}){return <label><span className="mb-1.5 block text-[10px] font-bold text-slate-300">{label}</span><textarea rows={4} maxLength={1000} value={value} onChange={e=>onChange(e.target.value)} placeholder={placeholder} className="w-full resize-none rounded-xl border border-slate-700 bg-slate-950/80 p-3 text-xs text-white outline-none placeholder:text-slate-600 focus:border-cyan-400"/></label>}
